name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install wasm-bindgen-cli
    - run: cargo build --target wasm32-unknown-unknown
    - name: Run
      run: wasm-pack build --target web
